### ISSUE TITLE
Error! ModuleNotFoundError: No module named 'better_proxy'

### ISSUE THREAD

**Issue by MinhHieu012** [AlexKrutoy/PixelTapBot#22]
Error:
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "/root/airdrop/pixeltap-git/PixelTapBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/airdrop/pixeltap-git/PixelTapBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/airdrop/pixeltap-git/PixelTapBot/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
ModuleNotFoundError: No module named 'better_proxy'

**Comment by Alexell** [comment]
`pip3 install -r requirements.txt` for solve this

**Comment by danisssimo94** [comment]
У меня это не сработало в термукс без Рут права, не могу запустить хамстеркомбатбот
